import test from 'node:test';
import assert from 'node:assert/strict';
import {eventHarness} from './liquidity-event-harness.js';
import * as runtime from '../../src/modules/bot/runtime.js';
import {handleCallbackQuery} from '../../src/modules/bot/routing/callback-router.js';
import {liquidityCatalogue} from '../../src/modules/liquidity/catalog.js';
import {initBot,stopBot} from '../../src/modules/bot/bot.js';
const route=async(f,data)=>{f.ctx.callbackQuery={data};await handleCallbackQuery(f.ctx);};
const healthy=()=>({time:Date.now(),levels:[[{px:'0.4',sz:'1000'}],[{px:'0.6',sz:'1000'}]]});
function many(f,n=100){f.meta.questions=[];f.meta.outcomes=Array.from({length:n},(_,i)=>({...f.meta.outcomes[0],outcome:100+i,name:`Candidate ${i}`}));}
function noManual(f){const s=runtime.userStates.get(f.owner);assert(!s.choices.some(a=>a.kind==='verify'));assert(!f.messages.at(-1).extra.reply_markup.inline_keyboard.flat().some(b=>/continue searching|retry|verify complete|продолжить поиск|повторить|проверить полностью/i.test(b.text)));}
function pick(f,kind){const s=runtime.userStates.get(f.owner),i=s.choices.findIndex(a=>a.kind===kind);assert(i>=0);const data=`liq:pick:${s.token}:${i}`;assert(f.messages.at(-1).extra.reply_markup.inline_keyboard.flat().some(b=>b.callback_data===data));return data;}
test('real Grammy sequential update handler remains free for immediate visible Cancel; shutdown drains owned discovery',{timeout:3000},async()=>{
 const f=eventHarness({routed:true,standalone:true});let pending;try{
  const bot=await initBot('123456:synthetic-test-token',f.owner);bot.botInfo={id:999,is_bot:true,first_name:'Fixture',username:'fixture_bot'};
  bot.api.config.use(async(prev,method,payload)=>{if(method==='editMessageText'||method==='sendMessage')f.messages.push({text:payload.text,extra:{reply_markup:payload.reply_markup}});return {ok:true,result:method==='answerCallbackQuery'?true:{message_id:1,date:0,chat:f.ctx.chat,text:payload.text}};});
  let entered,active=0;const held=new Promise(r=>entered=r);f.client.getOrderbook=async(coin,{signal})=>{active++;entered();return new Promise((_,reject)=>signal.addEventListener('abort',()=>{active--;reject(Error('Abort'));},{once:true}));};
  const update=(data,id)=>({update_id:id,callback_query:{id:String(id),from:f.ctx.from,chat_instance:'fixture',data,message:{message_id:1,date:0,chat:f.ctx.chat}}});
  pending=bot.handleUpdates([update('liq:new:live',1)]);await held;
  let completed=false;await Promise.race([pending.then(()=>completed=true),new Promise(r=>setTimeout(r,150))]);assert(completed,'Grammy polling must not wait for the whole liquidity scan before fetching Cancel');
  const state=runtime.userStates.get(f.owner),index=state.choices.findIndex(a=>a.kind==='cancel');assert(state.catalogueTask);await bot.handleUpdates([update(`liq:pick:${state.token}:${index}`,2)]);
  assert(!runtime.userStates.has(f.owner));assert.equal(active,0);assert.equal(f.actions.length,0);
  runtime.rateLimits.clear();const heldAgain=new Promise(r=>entered=r);await bot.handleUpdates([update('liq:new:live',3)]);await heldAgain;assert(active>0);await stopBot();assert.equal(active,0);assert(!runtime.userStates.get(f.owner)?.catalogueTask);
 }finally{await runtime.invalidateUserState(f.owner);await pending;runtime.rateLimits.clear();await f.close();}
});
test('all unsupported live price templates terminate with explicit strategy reason, not fabricated liquidity',async()=>{
 const f=eventHarness({routed:true,standalone:true});try{f.meta.outcomes[0].name='binaryPrice';f.meta.outcomes[0].description='perp:xyz:XYZ100|seconds:90|threshold:30870|time:20261009-2000';f.client.getOrderbook=async()=>assert.fail('Excluded strategy templates require no book work');await route(f,'liq:new:live');const {getTranslator}=await import('../../src/modules/i18n.js');assert(f.messages.at(-1).text.includes((await getTranslator('en'))('liq_assessment_live_price_unsupported')));noManual(f);assert(!runtime.userStates.get(f.owner).choices.some(a=>a.kind==='event'));assert.equal(f.actions.length,0);}finally{await f.close();}
});
test('one routed mode click crosses unavailable first windows and 95 weak to five qualified without manual work',async()=>{
 const f=eventHarness({routed:true,standalone:true});try{many(f);const reads=new Map();f.client.getOrderbook=async coin=>{reads.set(coin,(reads.get(coin)||0)+1);if(Number(coin.slice(1))<1050)throw Error('Transient book unavailable');return Number(coin.slice(1))<1950?{time:Date.now(),levels:[[],[]]}:healthy();};await route(f,'liq:new:live');const s=runtime.userStates.get(f.owner);assert.equal(s.choices.filter(a=>a.kind==='event').length,5);noManual(f);assert.equal(f.actions.length,0);assert([...reads.values()].every(n=>n<=2));console.log(JSON.stringify({fixture:'unknown first five, 90 weak, five healthy',clicks:1,requests:[...reads.values()].reduce((a,b)=>a+b,0)}));}finally{await f.close();}
});
for(const language of ['en','ru'])test(`50 mandatory books automatically verified before selection (${language})`,async()=>{
 const f=eventHarness({routed:true,standalone:true,language});try{many(f,25);f.meta.questions=[{question:55,name:'Large complete event',namedOutcomes:f.meta.outcomes.slice(0,-1).map(o=>o.outcome),fallbackOutcome:124,settledNamedOutcomes:[]}];let books=0;f.client.getOrderbook=async()=>{books++;return healthy();};await route(f,'liq:new:live');assert.equal(books,50);noManual(f);await route(f,pick(f,'event'));assert.equal(books,100);assert.equal(runtime.userStates.get(f.owner).state,'LIQUIDITY_INPUT');assert.equal(f.actions.length,0);}finally{await f.close();}
});
test('transient initial metadata and fees recover automatically; prolonged unavailable is terminal without retry buttons',async()=>{
 const f=eventHarness({routed:true,standalone:true});try{let meta=0,fees=0;f.client.getOutcomeMeta=async()=>{if(++meta===1)throw Error('Transient metadata');return structuredClone(f.meta);};f.client.getUserFees=async()=>{if(++fees===1)return {};return f.fees;};await route(f,'liq:new:live');assert(runtime.userStates.get(f.owner).choices.some(a=>a.kind==='event'));assert.equal(meta,2);assert.equal(fees,2);noManual(f);f.client.getUserFees=async()=>{fees++;throw Error('Unavailable');};await route(f,'liq:new:live');noManual(f);assert(!runtime.userStates.get(f.owner).choices.some(a=>a.kind==='event'));assert.equal(f.actions.length,0);}finally{await f.close();}
});
for(const action of ['event','menu','cancel'])test(`first qualified page is rendered before held remaining discovery; ${action} stops its transports and queued work`,{timeout:3000},async()=>{
 const f=eventHarness({routed:true,standalone:true});let pending;try{many(f,20);let entered,books=0,aborted=0,selecting=false;const held=new Promise(r=>entered=r);f.client.getOrderbook=async(coin,{signal})=>{books++;if(books<=10||selecting)return healthy();entered();return new Promise((_,reject)=>signal.addEventListener('abort',()=>{aborted++;reject(Error('Abort'));},{once:true}));};pending=route(f,'liq:new:live');await held;assert(runtime.userStates.get(f.owner).choices.some(a=>a.kind==='event'));assert(!runtime.userStates.get(f.owner).choices.some(a=>a.kind==='view'),'No candidate-window Continue disguised as Next');selecting=action==='event';await route(f,pick(f,action));await pending;const count=books,messages=f.messages.length;await new Promise(r=>setTimeout(r,80));assert(aborted>0);assert.equal(books,count);assert.equal(f.messages.length,messages);assert.equal(f.actions.length,0);assert(!runtime.userStates.get(f.owner)?.discoveryRun);if(selecting)assert.equal(runtime.userStates.get(f.owner).state,'LIQUIDITY_INPUT');else assert(!runtime.userStates.has(f.owner));}finally{await pending;await f.close();}
});
test('Next browses already-discovered qualified IDs only and refreshes both books, not unseen candidate windows',async()=>{
 const f=eventHarness({routed:true,standalone:true});try{many(f,20);let reads=[];f.client.getOrderbook=async coin=>{reads.push(coin);return Number(coin.slice(1))>=1050&&Number(coin.slice(1))<1150?{time:Date.now(),levels:[[],[]]}:healthy();};await route(f,'liq:new:live');assert.equal(reads.length,40);const s=runtime.userStates.get(f.owner);assert.equal(s.catalogIndex.length,10);assert(!s.discoveryRun);reads=[];await route(f,pick(f,'view'));assert.equal(reads.length,10);assert(reads.every(coin=>Number(coin.slice(1))>=1150));assert.equal(runtime.userStates.get(f.owner).choices.filter(a=>a.kind==='event').length,5);noManual(f);assert.equal(f.actions.length,0);}finally{await f.close();}
});
test('automatic terminal partial search obeys total read budget and unknown counts; membership holes counted once',async()=>{
 const f=eventHarness({standalone:true});try{many(f);f.meta.questions.push({question:99,namedOutcomes:[999],fallbackOutcome:998,settledNamedOutcomes:[]});let reads=0;f.client.getOrderbook=async()=>{reads++;return {time:Date.now(),levels:[[],[]]};};const r=await liquidityCatalogue(f.client,{automatic:true,maxDiscoveryBooks:20,onQualified:()=>assert.fail('No qualifying evidence')});assert.equal(reads,20);assert.equal(r.summary.weak,10);assert.equal(r.summary.unknown,1);assert.equal(r.summary.unscanned,90);assert.equal(r.summary.total,r.summary.qualified+r.summary.weak+r.summary.unknown+r.summary.unscanned);assert(r.discovery.terminal);}finally{await f.close();}
});
test('automatic hard deadline aborts all active books, queued reads and retries; no surviving worker',async()=>{
 const f=eventHarness({standalone:true});try{many(f);let reads=0,active=0;f.client.getOrderbook=async(coin,{signal})=>{reads++;active++;return new Promise((_,reject)=>signal.addEventListener('abort',()=>{active--;reject(Error('Abort'));},{once:true}));};const start=performance.now();await assert.rejects(liquidityCatalogue(f.client,{automatic:true,timeoutMs:100}),e=>e.code==='catalogue_deadline');assert(performance.now()-start<500);await new Promise(r=>setTimeout(r,120));assert.equal(active,0);assert(reads<=6);assert.equal(f.actions.length,0);}finally{await f.close();}
});
test('connected 80ms/read timing measures first qualified UI rather than empty response',async()=>{
 const f=eventHarness({routed:true,standalone:true});try{many(f);let books=0,meta=0,fees=0,first=null,peak=0,active=0;const start=performance.now(),edit=f.ctx.editMessageText;f.ctx.editMessageText=async(text,extra)=>{if(first===null&&extra.reply_markup.inline_keyboard.flat().some(b=>/^Candidate /.test(b.text)))first=Math.round(performance.now()-start);return edit(text,extra);};f.client.getOutcomeMeta=async()=>{meta++;return structuredClone(f.meta);};f.client.getUserFees=async()=>{fees++;return f.fees;};f.client.getOrderbook=async coin=>{books++;active++;peak=Math.max(peak,active);await new Promise(r=>setTimeout(r,80));active--;return Number(coin.slice(1))<1950?{time:Date.now(),levels:[[],[]]}:healthy();};await route(f,'liq:new:live');assert.notEqual(first,null);assert.equal(books,200);assert(peak<=6);noManual(f);console.log(JSON.stringify({fixture:'95 weak then 5 healthy; actual router; 80ms per book; representative fixture fees',firstQualifiedMs:first,totalMs:Math.round(performance.now()-start),userClicks:1,continueRetryVerifyClicks:0,totalReads:books+meta+fees,books,meta,fees,peak}));assert.equal(f.actions.length,0);}finally{await f.close();}
});
